### PR TITLE
Dark theme

### PR DESCRIPTION
**Pull request by gentleadam**
Began creating the config for the dark theme. Settings menu to toggle on and off. 

Requires some further work on changing the form colour.

### CODE REVIEW

**Comment by gllms** [comment]
I don't know if this half light / half dark theme is ready for the master branch already 🤔

**Comment by gllms** [comment]
That's better code, indeed.
But the dark menu's borders are still white, just like the status bar and the scrollbars. I don't know if we can make them all dark.

**Comment by milkshakespoon** [comment]
> That's better code, indeed.
> But the dark menu's borders are still white, just like the status bar and the scrollbars. I don't know if we can make them all dark.

Yeah for sure! I'm looking into it...

**Comment by gentleadam** [comment]
> > That's better code, indeed.
> > But the dark menu's borders are still white, just like the status bar and the scrollbars. I don't know if we can make them all dark.
> 
> Yeah for sure! I'm looking into it...

This is actually seemingly pretty tricky. It doesn't look like changing the border colours are nativity supported in Windows Forms. I see a few hacky things online... but don't seem to work properly.

**Comment by gllms** [comment]
We should probably transform Jottey into a WPF application. Like everyone on Reddit said.

**Comment by gentleadam** [comment]
> We should probably transform Jottey into a WPF application. Like everyone on Reddit said.

Agreed! I think that would give us the functions we need. How do you want to go about that?

**Comment by gllms** [comment]
I actually already started a "WPF" branch. I am making progress, because the interface and the automatic loading and saving from and to the temporary file already works. But I haven't pushed the changes to GitHub yet.

**Comment by gentleadam** [comment]
Deleted branch as the WPF merge is getting complex. Have created a new branch for this.

**Pull request closed without merging**
